heartML/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'heartML'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('survey', views.survey, name='survey'),
    path('prediction/<int:a>/<int:b>/<int:c>/<int:d>/<int:e>/<int:f>/<int:g>/<int:h>/<int:i>/<int:j>/<int:k>/<int:l>/<int:m>/<int:n>/<int:o>/<int:p>/<int:q>/', views.prediction, name="prediction"),
    path('prediction/', views.pred, name="pred"),
    path('goals/', views.goals, name="goals"),
    path('users/', include('users.urls')),
]

mh/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('heartML.urls')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    #Login page
    path('login/', auth_views.LoginView.as_view(), {'template_name': 'users/login.html'}, name='login'),

    #Logout page
    path('logout/', views.logout_view, name='logout'),

    #Registration page
    path('register/', views.register, name="register"),
]

heartML/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Goal(models.Model):
    text = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self): 
        self.text

class Person(models.Model): 
    gender = models.IntegerField()
    bmi = models.IntegerField()
    smoking = models.IntegerField()
    alcohol = models.IntegerField()
    stroke = models.IntegerField()
    phealth = models.IntegerField()
    mhealth = models.IntegerField()
    diffwalking = models.IntegerField()
    age = models.IntegerField()
    race = models.IntegerField()
    diabetes = models.IntegerField()
    pact = models.IntegerField()
    ghealth = models.IntegerField()
    sleep = models.IntegerField()
    asthma = models.IntegerField()
    kidney = models.IntegerField()
    skin = models.IntegerField()
    result = models.TextField(default='def')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1234)

    def getGender(self):
        if self.gender == 0:
            return "Male"
        return "Female"
    def getBmi(self):
        return self.bmi
    def getSmoking(self):
        return self.smoking==1
    def getAlcohol(self):
        return self.alcohol==1
    def getStroke(self):
        return self.stroke==1
    def getPhealth(self):
        return self.phealth
    def getMhealth(self):
        return self.mhealth
    def getDiffWalking(self):
        return self.diffwalking==1
    def getAge(self):
        age = self.age
        if age==0: return "18-24"
        elif age==1: return "25-29"
        elif age==2: return "30-34"
        elif age==3: return "35-39"
        elif age==4: return "40-44"
        elif age==5: return "45-49"
        elif age==6: return "50-54"
        elif age==7: return "55-59"
        elif age==8: return "60-64"
        elif age==9: return "65-69"
        elif age==10: return "70-74"
        elif age==11: return "75-79"
        else: return "80 or older"
    def getRace(self):
        race = self.race
        if race==0: return "White"
        elif race==1: return "Black"
        elif race==2: return "Hispanic"
        elif race==3: return "American Indian/Alaskan Native"
        elif race==4: return "Asian"
        else: return "Other"
    def getDiabetes(self):
        diabetes = self.diabetes
        if diabetes==3: return "Yes"
        elif diabetes==2: return "Yes (during pregnancy)"
        elif diabetes==1: return "No, borderline"
        else: return "No"
    def getPact(self):
        return self.pact==1
    def getGhealth(self):
        health = self.ghealth
        if health==0: return "Poor"
        elif health==1: return "Fair"
        elif health==2: return "Good"
        elif health==3: return "Very Good"
        else: return "Excellent"
    def getSleep(self):
        return self.sleep
    def getAsthma(self):
        return self.asthma==1
    def getKidney(self):
        return self.kidney==1
    def getSkin(self):
        return self.skin==1
    
    def getResult(self): 
        return self.result

    # def __str__(self):
    #     return self.result

heartML/views.py
from django.http import HttpResponseRedirect, Http404
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from django.shortcuts import render, get_object_or_404
from .models import Person, Goal

from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'Home.html') 

@login_required
def survey(request): 
    return render(request, 'ind.html')

@login_required
def goals(request):
    goals = Goal.objects.filter(owner=request.user)
    context = {'goals': goals}
    return render(request, 'goals.html', context)
    
@login_required
def pred(request): 
    # people = Person.objects.filter(owner=request.user)
    result = Person.objects.filter(owner=request.user)[:1].get().getResult()
    split = str(result).split("|")
    res = split[0]
    subtext = split[1]
    context = {'result': res, 'subtext': subtext}
    
    return render(request, 'index.html', context)
   
@login_required
def prediction(request, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q):
    new_input = [[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q]]
    data_path = 'heart_2020_cleaned.csv'
    healthData = pd.read_csv(data_path) 
    #healthData.drop('HeartDisease')
    healthData['AgeCategory'] = healthData['AgeCategory'].replace({'18-24':0,'25-29':1,'30-34':2,'35-39':3,'40-44':4,'45-49':5,'50-54':6,'55-59':7,'60-64':8,'65-69':9,'70-74':10,'75-79':11,'80 or older':12})
    healthData['Race'] = healthData['Race'].replace({'White':0, 'Black':1, 'Hispanic':2,'American Indian/Alaskan Native':3,'Asian':4,'Other':5})
    healthData['Smoking'] = healthData['Smoking'].replace({'No':0, 'Yes':1})
    healthData['AlcoholDrinking'] = healthData['AlcoholDrinking'].replace({'No':0, 'Yes':1})
    healthData['Stroke'] = healthData['Stroke'].replace({'No':0, 'Yes':1})
    healthData['DiffWalking'] = healthData['DiffWalking'].replace({'No':0, 'Yes':1})
    healthData['Sex'] = healthData['Sex'].replace({'Male':0, 'Female':1})
    healthData['PhysicalActivity'] = healthData['PhysicalActivity'].replace({'No':0, 'Yes':1})
    healthData['GenHealth'] = healthData['GenHealth'].replace({'Poor':0, 'Fair':1, 'Good': 2, 'Very good': 3, 'Excellent': 4})
    healthData['Asthma'] = healthData['Asthma'].replace({'No':0, 'Yes':1})
    healthData['KidneyDisease'] = healthData['KidneyDisease'].replace({'No':0, 'Yes':1})
    healthData['SkinCancer'] = healthData['SkinCancer'].replace({'No':0, 'Yes':1})
    healthData['Diabetic'] = healthData['Diabetic'].replace({'No':0, 'No, borderline diabetes': 1, 'Yes (during pregnancy)':2, 'Yes':3})
    healthData['HeartDisease'] = healthData['HeartDisease'].replace({'No':0, 'Yes': 1})
    feature_cols = ['Sex','BMI','Smoking', 'AlcoholDrinking', 'Stroke','PhysicalHealth', 'MentalHealth', 'DiffWalking','AgeCategory', 'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'SleepTime', 'Asthma', 'KidneyDisease', 'SkinCancer']
    X = healthData.loc[:, feature_cols]
    y = healthData.HeartDisease
    model = LogisticRegression(max_iter=10000)
    # fit model
    X_train , X_test, y_train, y_test = train_test_split(X,y,test_size=0.9,random_state=0)
    model.fit(X_train, y_train)
    result = ""
    subtext = ""
    new_output = model.predict(new_input)
    if(new_output == 1):
        result = "You are at risk for heart disease."
        subtext = "Although you are currently at risk, you can still reduce your chances by improving your health."
    else:
        result = "You are NOT at risk for heart disease."
        subtext = "Although you are currently not at risk, you can still reduce your chances by improving your health"
    
    res = result + "|" + subtext

    person = Person(gender=a,bmi=b,smoking=c,alcohol=d,stroke=e,phealth=f,mhealth=g,diffwalking=h,age=i,race=j,diabetes=k,pact=l,ghealth=m,sleep=n,asthma=o,kidney=p,skin=q, result=res, owner=request.user)
    person.save()

    goals = []
    descriptions = []

    #generating goals
    if(b>30):
        goals.append("BMI")
        d1 = "Your current BMI is " + str(b) + ". Ideally, you should target a BMI under 30 kg/m^2. In order to improve your BMI, exercise regularly and maintain a healthy diet."
        descriptions.append(d1)
    if(c==1):
        goals.append("Smoking")
        d2 = "Your current smoking habits contribute to your risk of develping heart disease. If you are addicted, get help by considering counseling."
        descriptions.append(d2)
    if(d==1): 
        goals.append("Alcohol")
        d3 = "Your current alcohol use contributes to your risk of developing heart disease. If you are addicted, get help by considering counseling."
        descriptions.append(d3)
    if(l==0):
        goals.append("Physical Activity")
        d4 = "Your lack of physical activity puts you at risk for heart disease. Aim for at least 150 min/week of aerobic activity/ Consider biking, swimming, and brisk walking."
        descriptions.append(d4)
    if(n<7):
        goals.append("Sleep")
        d5 = "You currently sleep " + str(n) + " hours per day. Lack of sleep increases your risk of heart disease, so target 7 hours of sleep every day. Prioritize your sleep by changing your daily routine."
        descriptions.append(d5)
    
    for i in range(len(goals)):
        goal = Goal(text = goals[i], description = descriptions[i], owner=request.user)
        goal.save()
        print("goal got saved")

    context = {
        'result': result,
        'subtext': subtext
    } 
    return render(request, 'index.html', context)

heartML/templates/Home.html
{% extends "base.html" %}


{% block header %}
<div class="container">
  <div class="jumbotron" style="background-color:#ebaeb1;">
    <!-- <img class="demo-bg" src="https://www.maycocolors.com/wp-content/uploads/2020/09/ss-141.jpg" alt=""> -->
    <h1 class="display-4">Do your part, care for your heart.</h1>
    <p class="lead">HeartML allows you to skip waiting lines to receive a quick diagnosis for heart disease.</p>
    <hr class="my-4">
    <p>With our AI-based prediction model, we use 17 health factors to determine your risk of developing heart disease.</p>
    <p class="lead">
      <a class="btn btn-danger btn-lg" href="{% url 'heartML:pred' %}" role="button">Learn more</a>
    </p>
  </div>

  {% load static %}
<style type="text/css">

  body {
      /* background-image: url("{% static 'background-image-lol.jpg' %}"); */
      background-repeat: no-repeat, repeat;
      background-position: center;
      background-size: cover;
  }

  .demo-bg {
    opacity: 0.23;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: auto;
  }

  .jumbotron {
      background-repeat: no-repeat, repeat;
      background-size: cover; 
      overflow: hidden;
      position: relative;
      font-weight: bold;
      box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);
  }

</style> 
  
</div>
{% endblock header %}

{% block content %}
  <h2>
    {% if user.is_authenticated %}
      <a href="{% url 'heartML:pred' %}" class="text-danger">Determine your risk</a> for heart disease and improve your health one day at a time. 
    {% else %} 
     <a href="{% url 'users:register' %}" class="text-danger">Register an account</a> to determine your risk for heart disease and improve your health one day at a time.
    {% endif %}
  </h2>
  <h2>
   Get personalized health goals to decrease your risk for developing heart disease. 
  </h2>
{% endblock content %}

heartML/templates/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html style="font-size: 16px;" lang="en">
  <head>
    <meta charset="utf-8"
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i">

    <title>HeartML</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <!--Static navbar-->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
        </div>

  
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><img src="{% static 'images/logo-transparent-png.png' %}" height="65px" width="65px"></li>
            <li><a href="{% url 'heartML:index' %}">Home</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'heartML:pred' %}">Prediction</a></li>
              <li><a href="{% url 'heartML:goals' %}">Personal Goals</a></li>
            {% endif %}
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'users:login' %}">Login</a></li>
              <li><a href="{% url 'users:register' %}">Register</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse-->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock header %} <!--NOTICE THAT THIS IS FOR THE JUMBOTRON-->
      </div>
      <div class="cont">
        {% block content %}{% endblock content %} <!--NOTICE THAT THIS IS FOR THE CONTENT-->
      </div>

    </div>

  </body>
</html>

<style>
  .navbar {
  min-height: 80px;
  }

.navbar-brand {
  padding: 0 15px;
  height: 80px;
  line-height: 80px;
}

.navbar-toggle {
  /* (80px - button height 34px) / 2 = 23px */
  margin-top: 23px;
  padding: 9px 10px !important;
}

@media (min-width: 768px) {
  .navbar-nav > li > a {
    /* (80px - line-height of 27px) / 2 = 26.5px */
    padding-top: 25px;
    padding-bottom: 25px;
    line-height: 30px;
    margin-right: 0;
    margin-left: 0;
  }
}
</style> 

heartML/templates/goals.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1>Goals</h1>
{% endblock header %}

{% block content %}

  <!-- <ul> -->
    {% for goal in goals %}
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3>
            {{ goal.text }}
          </h3>
        </div>

        <div class="panel-body">
          <h4>
          {{ goal.description|linebreaks }}
          </h4>
        </div>
      
      </div>
    {% empty %}
      <h4>
        Your data indicates that you have good health. Keep it up!
      </h4>
    {% endfor %}
  <!-- </ul> -->

{% endblock content %}

heartML/templates/index.html
{% load bootstrap3 %}
{% bootstrap_css %}

<!DOCTYPE html>
<html style="font-size: 16px;" lang="en"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="You are at risk for heart disease.">
    <meta name="description" content="">
    <title>HeartML</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
<link rel="stylesheet" href="{% static 'css/Home.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 5.4.4, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i">
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"logo": "images/logo-transparent-png.png"
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="HeartML">
    <meta property="og:type" content="website">
  <meta data-intl-tel-input-cdn-path="intlTelInput/"></head>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
        </button>
      </div>


      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><img src="{% static 'images/logo-transparent-png.png' %}" height="50px" width="50px"></li>
          <li><a href="{% url 'heartML:index' %}">Home</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'heartML:pred' %}">Prediction</a></li>
            <li><a href="{% url 'heartML:goals' %}">Personal Goals</a></li>
          {% endif %}
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li><a>Hello, {{ user.username }}.</a></li>
          <li><a href="{% url 'users:logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'users:login' %}">Login</a></li>
          <li><a href="{% url 'users:register' %}">Register</a></li>
          {% endif %}
        </ul>
      </div><!--/.nav-collapse-->

    </div>
  </nav>
  <body data-home-page="Home.html" data-home-page-title="HeartML" class="u-body u-xl-mode" data-lang="en">
    <section class="u-align-left u-clearfix u-white u-section-1" id="carousel_758d">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-text u-text-default u-text-1">{{result}}</h2>
        <p class="u-align-left u-custom-font u-font-roboto u-text u-text-2">{{subtext}}&nbsp;<br>Here are some ways you can reduce your risk:&nbsp;
        </p>
        <div class="u-expanded-width u-list u-list-1">
          <div class="u-repeater u-repeater-1">
            <div class="u-align-left u-container-style u-list-item u-palette-2-light-2 u-radius-16 u-repeater-item u-shape-round u-list-item-1">
              <div class="u-container-layout u-similar-container u-valign-top u-container-layout-1"><span class="u-file-icon u-icon u-icon-circle u-palette-2-base u-icon-1"><img src="{% static 'images/561611.png' %}" alt=""></span>
                <h4 class="u-text u-text-default u-text-3">Maintain a healthy diet</h4>
                <p class="u-text u-text-body-color u-text-default u-text-4">Reduce fat intake, increase fiber-intake. Your diet should include 5 servings of fresh fruit, vegetables and whole grains.</p>
              </div>
            </div>
            <div class="u-align-left u-container-style u-list-item u-palette-2-light-2 u-radius-16 u-repeater-item u-shape-round u-list-item-2">
              <div class="u-container-layout u-similar-container u-valign-top u-container-layout-2"><span class="u-file-icon u-icon u-icon-circle u-palette-2-base u-icon-2"><img src="{% static 'images/3271136.png' %}" alt=""></span>
                <h4 class="u-text u-text-default u-text-5">Increase physical activity</h4>
                <p class="u-text u-text-body-color u-text-default u-text-6">Regular exercise is the best way to maintian a healthy weight. Increasing physical activity lowers cholestrol levels and maintains blood pressure levels.&nbsp;</p>
              </div>
            </div>
            <div class="u-align-left u-container-style u-list-item u-palette-2-light-2 u-radius-16 u-repeater-item u-shape-round u-list-item-3">
              <div class="u-container-layout u-similar-container u-valign-top u-container-layout-3"><span class="u-file-icon u-icon u-icon-circle u-palette-2-base u-icon-3"><img src="{% static 'images/865779-86e1415a.png' %}" alt=""></span>
                <h4 class="u-text u-text-default u-text-7">Prioritize sleep</h4>
                <p class="u-text u-text-body-color u-text-default u-text-8">Most adults need at least 7 hours of sleep per night. Set a sleep schedule to reduce risk of obesity, high blood pressure, diabetes and depression.&nbsp;</p>
              </div>
            </div>
            <div class="u-align-left u-container-style u-list-item u-palette-2-light-2 u-radius-16 u-repeater-item u-shape-round u-list-item-4">
              <div class="u-container-layout u-similar-container u-valign-top u-container-layout-4"><span class="u-file-icon u-icon u-icon-circle u-palette-2-base u-icon-4"><img src="{% static 'images/752734.png' %}" alt=""></span>
                <h4 class="u-text u-text-default u-text-9">Reduce alcohol intake</h4>
                <p class="u-text u-text-body-color u-text-default u-text-10"> Do not drink more than 14 units a week. Avoiding alcohol altogether is the best way to reduce risk of heart disease.</p>
              </div>
            </div>
            <div class="u-align-left u-container-style u-list-item u-palette-2-light-2 u-radius-16 u-repeater-item u-shape-round u-list-item-5">
              <div class="u-container-layout u-similar-container u-valign-top u-container-layout-5"><span class="u-file-icon u-icon u-icon-circle u-palette-2-base u-icon-5"><img src="{% static 'images/3020101.png' %}" alt=""></span>
                <h4 class="u-text u-text-default u-text-11">Quit smoking</h4>
                <p class="u-text u-text-body-color u-text-default u-text-12"> Smoking is a major risk for developing heart disease. By quitting smoking, you will significantly improve your general health.</p>
              </div>
            </div>
            <div class="u-align-left u-container-style u-list-item u-palette-2-light-2 u-radius-16 u-repeater-item u-shape-round u-list-item-6">
              <div class="u-container-layout u-similar-container u-valign-top u-container-layout-6"><span class="u-file-icon u-icon u-icon-circle u-palette-2-base u-icon-6"><img src="{% static 'images/3389938.png' %}" alt=""></span>
                <h4 class="u-text u-text-default u-text-13">Control blood pressure</h4>
                <p class="u-text u-text-body-color u-text-default u-text-14"> You should target a blood pressure below 140/90mmHg. Check your blood pressure regularly and maintain a healthy diet.&nbsp;</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  
</body></html>